M48
; DRILL file KiCad 10.0.2-1.fc43 date 2026-05-25T12:00:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-25T12:00:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2-1.fc43
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X185.31Y-110.06
X191.09Y-110.06
T2
X126.5Y-59.0
X126.5Y-111.0
X220.0Y-58.9
X250.0Y-111.0
M30
